### ISSUE TITLE
Error while creating container

### ISSUE THREAD

**Issue by TurboCheetah** [Wonderfall/docker-searx#3]
While creating a container with the below `docker-compose` or `docker run -d --name searx -p 8888:8888 wonderfall/searx` I get `docker run -d --name searx -p $PORT:8888 wonderfall/searx`. What can I do, if anything, to fix it and deploy my instance?

`docker-compose`:
```services:
  searx:
    container_name: searx
    image: wonderfall/searx
    ports:
    - 8888:8888
    restart: unless-stopped
version: "3.4"
```

EDIT: I'm trying to run this on a raspberry pi if that helps.

**Comment by jodumont** [comment]
I would propose you to read [how to compose](https://docs.docker.com/compose/) a docker-compose.yml for the version 3

1. the docker-compose.yml file must be in a directory
2. this version of your docker-compose works
3. maybe your docker engine is not compatible with 3.4

```docker-compose.yml
version: "3.4"

services:

  searx:
    container_name: searx
    image: wonderfall/searx
    ports:
    - 8888:8888
    restart: unless-stopped
```

**Comment by TurboCheetah** [comment]
That wasn't my full compose, only the searx section. It worked on a DigitalOcean vps, the problem was that it won't run on arm cpus.

**Comment by jodumont** [comment]
I'm glad you found your mistake
